package com.overdrive.app.config

import android.system.ErrnoException
import android.system.Os
import android.system.OsConstants
import android.util.Log
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.io.FileOutputStream
import java.io.IOException
import java.nio.charset.StandardCharsets
import java.util.concurrent.atomic.AtomicLong
import com.overdrive.app.util.ScratchPaths

/**
 * Single source of truth for Overdrive's settings backup / restore.
 *
 * ARCHITECTURE — one core, three surfaces (mirrors the OTA update feature):
 * the export/restore logic is defined ONLY here, inside the camera-daemon
 * process (UID 2000, the sole process that can atomic-rename in sticky
 * /data/local/tmp/). Every surface is a thin adapter that calls this via the
 * daemon's IPC commands (SurveillanceIpcServer EXPORT_CONFIG / REPLACE_CONFIG):
 *   - Web      → ConfigBackupApiHandler (runs in-process, calls directly)
 *   - App UI   → UnifiedConfigManager IPC client → REPLACE_CONFIG
 *   - Telegram → BackupCommandHandler → ctx.sendIpcCommand(19877, …)
 * Nothing is duplicated; the adapters are pure transport.
 *
 * SCOPE — SAME-DEVICE restore only (called out in the UI). Because the bundle
 * is restored onto the same head-unit/vehicle, the cross-device hazards
 * (vehicle-specific camera HAL ids, tunnel-token split-brain) do NOT apply, so
 * those keys are carried verbatim. The remaining hazards are write-path, not
 * data: see [applyBundle].
 *
 * SECRETS — device-bound encrypted credentials (BYD Cloud, navigation,
 * Telegram, and GenAI API keys) are stored as their `ENC:` blobs and
 * the bundle ALSO snapshots the device-id file (.byd_device_id) that
 * CredentialCipher derives its key from. Restoring the DID first lets the
 * blobs decrypt again even after a factory reset. TRADEOFF: the bundle then
 * contains key material, so the export endpoint MUST stay LOCAL-mode + JWT
 * gated and the UI MUST warn the user to keep the file private.
 */
object ConfigBackupService {
    private const val TAG = "ConfigBackup"

    const val BUNDLE_FORMAT = "overdrive-config-bundle"
    const val BUNDLE_VERSION = 1
    // Bump when applyBundle's understood schema changes incompatibly. A bundle
    // with a HIGHER schemaVersion than this is refused (forward-incompatible).
    const val SCHEMA_VERSION = 1

    // CredentialCipher.DID_PATH — duplicated as a literal rather than exposing
    // it, to keep this class free of a crypto dependency. Must match
    // CredentialCipher.java:29.
    private val DID_PATH = ScratchPaths.path(".byd_device_id")
    private val RESTORE_JOURNAL_PATH =
        ScratchPaths.path(".overdrive_config_restore_txn.json")
    private const val RESTORE_JOURNAL_VERSION = 1
    private val didTempSequence = AtomicLong(0)
    private val restoreJournalTempSequence = AtomicLong(0)

    // Runtime/coordination keys that are meaningless or harmful to restore even
    // on the same device. Stripped on BOTH export and import (defence in depth
    // against a hand-edited bundle). Path form: "section.key".
    private val EPHEMERAL_KEYS = listOf(
        "navMap.clusterMapActive",   // daemon↔activity runtime flag; stale=ghost map
        "chargingAnalytics.pendingTariffReprices",
        "chargingAnalytics.pendingTariffRepriceTokens",
    )

    // Whole top-level keys never carried in a bundle.
    //  - updates: the OTA channel must stay whatever THIS install compiled with
    //    (restoring "alpha" into a stable build pulls alpha APKs).
    //  - lastModified / version: regenerated by the config layer on write.
    //  - configSeq: the monotonic write sequence is install-local durability
    //    state (UnifiedConfigManager). A restore must NEVER inject a foreign seq
    //    — that could wedge the highest-seq-wins recovery/promotion ordering.
    //    Stripped on export + skipped on import; the live config keeps its own
    //    seq and saveConfig bumps it past the prior value on write.
    private val EXCLUDED_SECTIONS = listOf(
        "updates",
        "lastModified",
        "version",
        "configSeq",
        "__overdriveMutationClocks",
    )

    // Sections whose secret fields are device-bound `ENC:` blobs. If the DID
    // could NOT be restored (writeDid failed), overlaying these would replace
    // the user's CURRENTLY-WORKING credentials with blobs that can no longer
    // decrypt (key derives from the DID) — actively making things worse. In
    // that one case we skip them so the live credentials survive.
    private val CREDENTIAL_SECTIONS =
        listOf("bydCloud", "navMap", "telegram", "genAi")

    // Recursion cap for [deepMergeInto] — guards against a pathological
    // hand-edited bundle with deeply nested objects. Real config nesting is
    // <= 2 levels (e.g. geocoding.recording.enabled), so 6 is generous.
    private const val MAX_MERGE_DEPTH = 6

    // Dotted paths whose direct CHILD objects are ATOMIC values (discriminated
    // unions / opaque records), NOT mergeable maps. deepMergeInto replaces such
    // a child wholesale instead of recursing into it — otherwise a child that
    // changed shape between export and the live config (e.g. a camera role that
    // switched from a panoramic_slice ref to a direct ref) would keep the
    // live-only variant field (a stale `slice` left beside a new `cameraId`),
    // producing a hybrid record. camera.roleMappings maps <role> → CameraSourceRef,
    // a "kind"-discriminated union (CameraSourceRef.toJson emits only the fields
    // for its kind), so each role value must be replaced atomically.
    private val ATOMIC_CHILD_PARENT_PATHS = setOf("camera.roleMappings")

    /**
     * Recursively overlay [incoming] onto [base], in place. For each key: if
     * BOTH sides hold a JSONObject, recurse (preserving live sub-keys the
     * bundle predates); otherwise the incoming value overrides. Beyond
     * [MAX_MERGE_DEPTH] it falls back to a wholesale put (depth-1 behaviour) so
     * a malicious deeply-nested bundle can't blow the stack.
     *
     * [path] is the dotted path of [base] (""/"camera"/"camera.roleMappings").
     * When [path] is in [ATOMIC_CHILD_PARENT_PATHS], each child is REPLACED
     * wholesale rather than merged, so discriminated-union records don't end up
     * with stale variant fields.
     *
     * Trade-off (by design): a sub-key the user DELETED post-export is NOT
     * removed by restore — additive-merge is the correct fix for the silent
     * sub-key LOSS this replaces; honouring deletes would require a tombstone
     * the bundle format doesn't carry.
     */
    private fun deepMergeInto(base: JSONObject, incoming: JSONObject, path: String = "", depth: Int = 0) {
        val mergeChildrenAtomically = path in ATOMIC_CHILD_PARENT_PATHS
        val keys = incoming.keys()
        while (keys.hasNext()) {
            val k = keys.next()
            val iv = incoming.get(k)
            val bv = base.opt(k)
            if (iv is JSONObject && bv is JSONObject && depth < MAX_MERGE_DEPTH
                    && !mergeChildrenAtomically) {
                deepMergeInto(bv, iv, if (path.isEmpty()) k else "$path.$k", depth + 1)
            } else {
                base.put(k, iv)
            }
        }
    }

    // ==================== EXPORT ====================

    /**
     * Build a backup bundle from the live config + the device-id file.
     * Runs in the daemon process. Returns a JSONObject ready to serialise.
     *
     * WHAT THE BUNDLE CONTAINS (so the privacy surface is explicit):
     *  - Every unified-config section EXCEPT [EXCLUDED_SECTIONS] and the
     *    [EPHEMERAL_KEYS]. That includes credential sections whose secret
     *    fields are stored as `ENC:` blobs — bydCloud (username + login/sign
     *    keys + password), navMap.routingApiKey, telegram.botToken, and
     *    genAi.apiKey. The
     *    username/identity fields are NOT encrypted. This is acceptable ONLY
     *    because the feature is same-device and the export endpoints are
     *    LOCAL-mode + JWT gated; the UI warns the file holds credentials.
     *  - The device-id (.byd_device_id) so the `ENC:` blobs stay decryptable
     *    after a factory reset (CredentialCipher binds its key to the DID).
     * WHAT IT DOES NOT CONTAIN:
     *  - SafeLocation home/work GPS — stored in the separate file
     *    /data/local/tmp/safe_locations.json, deliberately not bundled.
     *  - Tunnel tokens (.zrok/.tailscale), the OTA channel, runtime flags.
     */
    @JvmStatic
    @JvmOverloads
    fun buildBundle(appVersion: String, deviceModel: String, nowMs: Long,
                    includeTrips: Boolean = false): JSONObject {
        // Config and credential key material are one export snapshot. A restore
        // cannot interleave and pair settings from one revision with another DID.
        val snapshot = UnifiedConfigManager.runUnderConfigLock {
            val unified = JSONObject(
                UnifiedConfigManager.readDurableConfigStrict().toString())
            for (sec in EXCLUDED_SECTIONS) unified.remove(sec)
            stripEphemeral(unified)
            ExportSnapshot(unified, readDidSnapshotStrict())
        }

        val categories = org.json.JSONArray().put("settings")

        val manifest = JSONObject()
            .put("format", BUNDLE_FORMAT)
            .put("bundleVersion", BUNDLE_VERSION)
            .put("schemaVersion", SCHEMA_VERSION)
            .put("appVersion", appVersion)
            .put("deviceModel", deviceModel)
            .put("fingerprint", safeFingerprint())
            .put("exportedAtMs", nowMs)
            .put("sameDeviceOnly", true)

        val bundle = JSONObject()
            .put("manifest", manifest)
            .put("settings", JSONObject().put("unified", snapshot.unified))

        // Snapshot the DID so the ENC: secrets remain decryptable after a
        // factory reset. Best-effort: absent DID just means secrets fall back
        // to re-entry on a reset (they still decrypt on a non-reset restore).
        didValue(snapshot.did)?.let { bundle.put("did", it) }

        // Opt-in trips category (stats only — no telemetry files). The trips DB
        // lives in the daemon; pulled via the manager. Best-effort: if the
        // manager/DB isn't up, the category is simply omitted.
        if (includeTrips) {
            try {
                val tam = com.overdrive.app.daemon.CameraDaemon.getTripAnalyticsManager()
                val db = tam?.database
                if (db != null && db.isAvailable) {
                    val trips = db.exportTripsJson()
                    bundle.put("trips", trips)
                    categories.put("trips")
                    Log.i(TAG, "Bundle includes ${trips.length()} trips (stats-only)")
                } else {
                    Log.w(TAG, "Trips requested but DB unavailable; omitting category")
                }
            } catch (e: Exception) {
                Log.w(TAG, "Trips export skipped: ${e.message}")
            }
        }
        manifest.put("categories", categories)

        Log.i(TAG, "Built backup bundle (appVersion=$appVersion, model=$deviceModel, " +
            "didIncluded=${bundle.has("did")})")
        return bundle
    }

    // ==================== IMPORT ====================

    data class ApplyResult(val success: Boolean, val message: String, val warnings: List<String>)
    private data class ExportSnapshot(
        val unified: JSONObject,
        val did: DidSnapshot,
    )
    private data class DidSnapshot(
        val existed: Boolean,
        val bytes: ByteArray,
    )
    private data class DidWriteResult(
        val usable: Boolean,
        val changed: Boolean,
    )
    private data class RestoreTransaction(
        val success: Boolean,
        val didUsable: Boolean,
        val didChanged: Boolean,
        val secretsDecryptable: Boolean,
        val skipSections: Set<String>,
    )
    private class SohLineageResetException(
        message: String,
        cause: Throwable? = null,
    ) : IllegalStateException(message, cause)

    /**
     * Validate a bundle WITHOUT writing anything. Used by the import-preview
     * endpoint so the UI can show compatibility warnings + a confirm step.
     */
    @JvmStatic
    fun validateBundle(bundle: JSONObject, currentAppVersion: String, currentModel: String): ApplyResult {
        val warnings = ArrayList<String>()
        val manifest = bundle.optJSONObject("manifest")
            ?: return ApplyResult(false, "Not an Overdrive backup (missing manifest).", warnings)
        if (BUNDLE_FORMAT != manifest.optString("format")) {
            return ApplyResult(false, "Unrecognised file format.", warnings)
        }
        if (manifest.optInt("schemaVersion", Int.MAX_VALUE) > SCHEMA_VERSION) {
            return ApplyResult(false,
                "This backup is from a newer Overdrive version. Update the app first.", warnings)
        }
        val unifiedForCheck = bundle.optJSONObject("settings")?.optJSONObject("unified")
            ?: return ApplyResult(false, "Backup contains no settings.", warnings)
        // Every config section is a JSON object. Reject a hand-edited/corrupt
        // bundle that carries a scalar where a section object belongs (e.g.
        // {"surveillance": 123}) — overlaying it would replace the live section
        // object with a scalar and make every getJSONObject("surveillance")
        // reader throw. (Top-level scalars like version/lastModified are excluded
        // from the overlay anyway, but the bundle shouldn't contain unified-level
        // scalar sections at all.)
        val badKeys = unifiedForCheck.keys().asSequence().filter { k ->
            !EXCLUDED_SECTIONS.contains(k) && unifiedForCheck.opt(k) !is JSONObject
        }.toList()
        if (badKeys.isNotEmpty()) {
            return ApplyResult(false,
                "Backup is malformed (invalid section: ${badKeys.first()}).", warnings)
        }
        // Same-device advisories (non-blocking — user confirms).
        val bundleModel = manifest.optString("deviceModel", "")
        if (bundleModel.isNotEmpty() && bundleModel != currentModel) {
            warnings.add("Backup was made on a different vehicle model ($bundleModel vs $currentModel). " +
                "Camera/blind-spot calibration may not match.")
        }
        // Firmware change breaks credential decryption regardless of the DID:
        // CredentialCipher's key = SHA256(salt:DID:Build.FINGERPRINT), so a
        // changed fingerprint derives a different key and the ENC: secrets
        // decrypt to "" (silently). Warn whenever the fingerprint differs —
        // the earlier "&& !bundle.has(did)" guard was backwards (on a same-
        // device restore the DID is ALWAYS present, so the warning never fired
        // for the very case that needs it).
        // Warn only about credentials the bundle CARRIES that actually fail to
        // decrypt under the current key — mirroring apply-time, which gates on a
        // real test-decrypt (NOT on a bare fingerprint change). A stable-key
        // blob decrypts fine post-OTA, so a fingerprint change alone must not
        // scare the user about credentials that will restore correctly.
        val carriedUndecryptable = CREDENTIAL_SECTIONS.filter {
            sectionHasEncryptedSecret(unifiedForCheck, it) &&
                !sectionSecretDecryptsClean(unifiedForCheck, it)
        }
        if (carriedUndecryptable.isNotEmpty()) {
            val names = carriedUndecryptable.joinToString(", ") { credentialLabel(it) }
            val bundleFp = manifest.optString("fingerprint", "")
            val fpHint = if (bundleFp.isNotEmpty() && bundleFp != safeFingerprint())
                " (device firmware changed since this backup)" else ""
            warnings.add("These saved credentials could not be decrypted$fpHint and may " +
                "need re-entering: $names.")
        }
        val bundleApp = manifest.optString("appVersion", "")
        if (bundleApp.isNotEmpty() && bundleApp != currentAppVersion) {
            warnings.add("Backup is from app version $bundleApp (current $currentAppVersion).")
        }
        // NOTE: a DID mismatch (bundle.did != current .byd_device_id) is
        // deliberately NOT warned here. Unlike a fingerprint change (which we
        // can't undo), applyBundle RESTORES the bundle's DID before writing the
        // config, so the ENC: secrets decrypt correctly afterwards — a preview
        // warning would be a false alarm. The only genuine failure is writeDid()
        // itself failing during apply; that is surfaced as a runtime warning in
        // applyBundle's skip-and-warn path, not predicted here.
        return ApplyResult(true, "Backup looks valid.", warnings)
    }

    /**
     * Apply a bundle. DAEMON-ONLY caller (UID 2000) — this performs the atomic
     * whole-config write. Order matters:
     *   1. Journal the prior config+DID and publish a credential-free bridge.
     *   2. Restore the DID, verify imported secrets, and build the merged root.
     *   3. Atomic whole-object save via UnifiedConfigManager.saveConfig, then
     *      durably clear the journal.
     *
     * R8 (corruption latch): saveConfig refuses if a prior load latched
     * corruption. We forceReload() first; a clean load clears the latch. If it
     * stays latched the on-disk file is genuinely unparseable — we surface that
     * rather than silently failing.
     */
    @JvmStatic
    fun applyBundle(bundle: JSONObject, currentAppVersion: String, currentModel: String): ApplyResult {
        val validation = validateBundle(bundle, currentAppVersion, currentModel)
        if (!validation.success) return validation
        // validateBundle returns an immutable-intent list; copy so we can append
        // a runtime warning (DID restore failure) discovered during apply.
        val warnings = ArrayList(validation.warnings)

        val incomingRaw = bundle.optJSONObject("settings")?.optJSONObject("unified")
            ?: return ApplyResult(false, "Backup contains no settings.", warnings)
        // Runtime obligations belong to this installation. Strip them only from
        // the incoming image; stripping the merged root would erase a currently
        // pending durable tariff reprice.
        val incoming = JSONObject(incomingRaw.toString())
        stripEphemeral(incoming)

        val fpChanged = run {
            val fp = bundle.optJSONObject("manifest")?.optString("fingerprint", "") ?: ""
            fp.isNotEmpty() && fp != safeFingerprint()
        }

        val transaction = try {
            UnifiedConfigManager.runUnderConfigLock {
                recoverInterruptedRestoreUnderConfigLock()
                val priorDid = readDidSnapshotStrict()
                // Exact fresh bytes when valid; only genuinely absent or
                // malformed config may use a seeded restore base.
                val current =
                    UnifiedConfigManager.readDurableConfigForRestore()
                val didWrite = if (bundle.has("did")
                        && bundle.optString("did", "").isNotEmpty()) {
                    beginBundledDidTransition(
                        bundle.optString("did"), priorDid, current)
                } else {
                    DidWriteResult(usable = true, changed = false)
                }

                try {
                    // Prove every carried credential against the DID that will
                    // accompany the restored config.
                    val secretsDecryptable =
                        didWrite.usable && bundleSecretsDecrypt(incoming)
                    val skipSections =
                        if (didWrite.usable && secretsDecryptable) emptySet()
                        else CREDENTIAL_SECTIONS.toSet()

                    val toWrite = JSONObject(current.toString())

                    val sectionKeys = incoming.keys()
                    while (sectionKeys.hasNext()) {
                        val k = sectionKeys.next()
                        if (EXCLUDED_SECTIONS.contains(k)
                                || skipSections.contains(k)
                                || (didWrite.changed
                                    && CREDENTIAL_SECTIONS.contains(k))) continue
                        val incomingVal = incoming.get(k)
                        val baseVal = toWrite.opt(k)
                        if (incomingVal is JSONObject && baseVal is JSONObject) {
                            deepMergeInto(baseVal, incomingVal, k)
                            toWrite.put(k, baseVal)
                        } else {
                            toWrite.put(k, incomingVal)
                        }
                    }
                    replaceCredentialSectionsAfterDidChange(
                        toWrite,
                        incoming,
                        skipSections,
                        didWrite.changed,
                    )
                    for (sec in EXCLUDED_SECTIONS) {
                        if (!toWrite.has(sec) && current.has(sec)) {
                            toWrite.put(sec, current.get(sec))
                        }
                    }

                    try {
                        val restoredTrips = toWrite.optJSONObject("tripAnalytics")
                        val bundleTrips = incoming.optJSONObject("tripAnalytics")
                        if (restoredTrips != null && bundleTrips != null
                                && bundleTrips.has("enabled")) {
                            restoredTrips.remove("enabledDefaultMigrated")
                        }
                    } catch (e: Exception) {
                        Log.w(TAG, "trips migration-marker reset failed: ${e.message}")
                    }

                    UnifiedConfigManager.ensureDefaults(toWrite)

                    // A model-lineage boundary is durable before the new model
                    // identity can become durable. A crash between these writes
                    // leaves either old-model+cleared-SOH or new-model+cleared-SOH.
                    if (resolvedVehicleModelId(current)
                            != resolvedVehicleModelId(toWrite)) {
                        resetSohForModelRestore()
                    }

                    val saved = UnifiedConfigManager.saveConfig(
                        toWrite, /* force = */ true)
                    if (didWrite.changed) {
                        if (saved) {
                            clearRestoreJournal()
                        } else {
                            recoverInterruptedRestoreUnderConfigLock()
                        }
                    }
                    RestoreTransaction(
                        success = saved,
                        didUsable = didWrite.usable,
                        didChanged = didWrite.changed,
                        secretsDecryptable = secretsDecryptable,
                        skipSections = skipSections,
                    )
                } catch (t: Throwable) {
                    if (File(RESTORE_JOURNAL_PATH).exists()) {
                        try {
                            recoverInterruptedRestoreUnderConfigLock()
                        } catch (rollbackFailure: Throwable) {
                            throw IOException(
                                "Restore failed and write-ahead rollback failed",
                                rollbackFailure,
                            )
                        }
                    }
                    throw t
                }
            }
        } catch (t: Throwable) {
            Log.e(TAG, "Backup restore transaction failed: ${t.message}", t)
            val message = if (t is SohLineageResetException) {
                "Could not restore settings because battery-health model lineage " +
                    "could not be reset durably."
            } else {
                "Could not write settings. The config may be locked or damaged — " +
                    "try again after restarting the camera service."
            }
            return ApplyResult(false, message, warnings)
        }

        if (!transaction.success) {
            return ApplyResult(false,
                "Could not write settings. The config may be locked or damaged — " +
                "try again after restarting the camera service.", warnings)
        }

        if (transaction.skipSections.isNotEmpty()) {
            val dropped = transaction.skipSections.filter {
                sectionHasEncryptedSecret(incoming, it)
            }
            if (dropped.isNotEmpty()) {
                val names = dropped.joinToString(", ") { credentialLabel(it) }
                val reason = when {
                    !transaction.didUsable -> "the device key could not be restored"
                    fpChanged -> "the saved credentials could not be decrypted " +
                        "(device firmware changed since this backup)"
                    else -> "the saved credentials could not be decrypted"
                }
                val disposition = if (transaction.didChanged) {
                    "and credentials encrypted with the previous device key were cleared"
                } else {
                    "and your current ones were kept"
                }
                warnings.add("Because $reason, these saved credentials were not restored " +
                    "$disposition — re-enter if needed: $names.")
            }
        }

        // The whole-config write bypasses the charging API callback, so its
        // manager-owned config and tariff snapshots otherwise keep the pre-restore
        // values until process restart. Reload outside the config lock: the callback
        // can perform database/lifecycle work and strict tariff reads of its own.
        try {
            val chargingManager =
                com.overdrive.app.daemon.CameraDaemon.getChargingSessionManager()
            val chargingReloaded = chargingManager?.onConfigRestored()
                ?: com.overdrive.app.charging.TariffManager.getInstance().load()
            if (!chargingReloaded) {
                warnings.add("Settings were restored, but charging analytics could not " +
                    "reload them. Restart the camera service before relying on charging rates.")
            }
        } catch (t: Throwable) {
            Log.w(TAG, "Charging runtime reload after restore failed: ${t.message}")
            warnings.add("Settings were restored, but charging analytics could not " +
                "reload them. Restart the camera service before relying on charging rates.")
        }

        // Trips read the tariff at finalize time from the restored config, so a
        // restore needs no separate pricing reconciliation here.

        // Trips category (opt-in, stats-only). Replayed AFTER the config save so
        // a settings restore never depends on the trips DB being up. Idempotent
        // + deduped inside importTripsJson, so a partial/duplicate import is
        // safe. Runs outside the config file lock — it's a different DB with its
        // own connection serialization. Best-effort: a trips failure never fails
        // the settings restore (which already succeeded above).
        val tripsArr = bundle.optJSONArray("trips")
        if (tripsArr != null && tripsArr.length() > 0) {
            try {
                val tam = com.overdrive.app.daemon.CameraDaemon.getTripAnalyticsManager()
                val db = tam?.database
                if (db != null && db.isAvailable) {
                    val n = db.importTripsJson(tripsArr)
                    Log.i(TAG, "Restored $n trips from bundle")
                    if (n > 0) warnings.add("Imported $n trip(s) into your history " +
                        "(detailed per-trip telemetry is not included in backups).")
                } else {
                    warnings.add("Trip history could not be restored — the trips service " +
                        "wasn't ready. Restart the camera daemon and re-import.")
                }
            } catch (e: Exception) {
                Log.w(TAG, "Trips import failed: ${e.message}")
                warnings.add("Trip history could not be restored (${e.message}).")
            }
        }

        Log.i(TAG, "Backup applied (warnings=${warnings.size})")
        return ApplyResult(true, "Settings restored.", warnings)
    }

    // ==================== helpers ====================

    /** True if the named section in [unified] carries an `ENC:` credential blob.
     *  Lets the skip-warning name only the credentials the bundle ACTUALLY held,
     *  rather than a blanket token-count message. */
    private fun sectionHasEncryptedSecret(unified: JSONObject, section: String): Boolean {
        val obj = unified.optJSONObject(section) ?: return false
        return obj.toString().contains("\"ENC:")
    }

    /**
     * Verify the bundle's credential sections actually decrypt under the
     * current device key. Finds the first `ENC:` blob across the credential
     * sections and attempts to decrypt it. Returns:
     *   - true  if there are no ENC: blobs (nothing to lose), or one decrypts
     *           to real plaintext
     *   - false if an ENC: blob is present but decrypt does NOT yield usable
     *           plaintext (wrong key, or a malformed/too-short blob)
     *
     * NOTE on the failure check: CredentialCipher.decrypt returns "" on a
     * key/MAC mismatch, BUT for a malformed blob (Base64 payload shorter than
     * IV+tag) it returns the ORIGINAL "ENC:…" string unchanged rather than "".
     * So "non-empty" alone is NOT proof of success — a returned value that is
     * still an ENC: blob (or byte-identical to the input) means decryption did
     * not actually happen. Treat both as failure so a corrupted/tampered bundle
     * can't pass validation and overwrite working credentials with garbage.
     * Cheap (one AES-GCM open) and only runs on restore.
     */
    private fun bundleSecretsDecrypt(unified: JSONObject): Boolean {
        // Check EVERY ENC: blob across ALL credential sections, not just the
        // first — a bundle could carry a valid bydCloud blob and a tampered
        // navMap/telegram/genAi one; an early return on the first success would let
        // the corrupt later blob through. Any blob that fails to yield real
        // plaintext fails the whole validation (→ skip credentials, keep live).
        for (section in CREDENTIAL_SECTIONS) {
            if (!sectionSecretDecryptsClean(unified, section)) return false
        }
        return true   // no ENC: blobs, or all of them decrypted cleanly
    }

    /**
     * True if every ENC: blob in [section] decrypts to real plaintext under the
     * current device key (or the section carries none). Mirrors the per-blob
     * success test in [bundleSecretsDecrypt]. Used by the validate-preview so a
     * fingerprint change alone doesn't warn about credentials that will in fact
     * restore (stable-key blobs decrypt fine post-OTA).
     */
    private fun sectionSecretDecryptsClean(unified: JSONObject, section: String): Boolean {
        val obj = unified.optJSONObject(section) ?: return true
        val keys = obj.keys()
        while (keys.hasNext()) {
            val v = obj.opt(keys.next())
            if (v is String &&
                com.overdrive.app.byd.cloud.crypto.CredentialCipher.isEncrypted(v)) {
                val ok = try {
                    val out = com.overdrive.app.byd.cloud.crypto.CredentialCipher.decrypt(v)
                    // Success ONLY if we got real plaintext: non-empty, not the
                    // original blob echoed back, and no longer ENC:-tagged.
                    out.isNotEmpty() && out != v &&
                        !com.overdrive.app.byd.cloud.crypto.CredentialCipher.isEncrypted(out)
                } catch (e: Exception) {
                    false
                }
                if (!ok) return false
            }
        }
        return true
    }

    /** Human label for a credential section, for the re-entry warning. */
    private fun credentialLabel(section: String): String = when (section) {
        "bydCloud" -> "BYD Cloud login"
        "navMap"   -> "navigation API key"
        "telegram" -> "Telegram bot token"
        "genAi"    -> "GenAI provider API key"
        else        -> section
    }

    private fun stripEphemeral(root: JSONObject) {
        for (path in EPHEMERAL_KEYS) {
            val dot = path.indexOf('.')
            if (dot <= 0) continue
            val section = path.substring(0, dot)
            val key = path.substring(dot + 1)
            root.optJSONObject(section)?.remove(key)
        }
    }

    /**
     * Credential ciphertext is bound to the DID. Once the DID changes, no field
     * from the prior root may cross into the committed image through additive
     * merge. Verified incoming sections replace their live counterparts as
     * complete objects; absent or rejected sections remain absent.
     */
    private fun replaceCredentialSectionsAfterDidChange(
        target: JSONObject,
        verifiedIncoming: JSONObject,
        rejectedSections: Set<String>,
        didChanged: Boolean,
    ) {
        if (!didChanged) return
        for (section in CREDENTIAL_SECTIONS) {
            target.remove(section)
            if (rejectedSections.contains(section)) continue
            val replacement = verifiedIncoming.optJSONObject(section) ?: continue
            target.put(section, JSONObject(replacement.toString()))
        }
    }

    private fun safeFingerprint(): String = try {
        android.os.Build.FINGERPRINT ?: "unknown"
    } catch (e: Exception) { "unknown" }

    private fun resolvedVehicleModelId(root: JSONObject): String? {
        val vehicle = root.optJSONObject("vehicle") ?: return null
        return VehicleModelSelection.resolvedModelId(
            vehicle.optString("modelId", ""),
            vehicle.optString("modelSource", ""),
        )
    }

    private fun resetSohForModelRestore() {
        val estimator = try {
            com.overdrive.app.monitor.SocHistoryDatabase.getInstance()
                ?.getSohEstimator()
        } catch (t: Throwable) {
            throw SohLineageResetException(
                "SOH estimator is unavailable for model-changing restore", t)
        } ?: throw SohLineageResetException(
            "SOH estimator is unavailable for model-changing restore")
        try {
            estimator.reset()
        } catch (t: Throwable) {
            throw SohLineageResetException(
                "SOH estimator reset was not durable", t)
        }
    }

    /**
     * Recover an interrupted cross-file restore. The caller must hold
     * UnifiedConfigManager's stable config lock.
     *
     * Both forward progress and rollback pass through a config with credential
     * sections removed. Therefore a process death can expose old credentials
     * with the old DID, new credentials with the new DID, or no credentials,
     * but never encrypted credentials paired with the wrong DID.
     */
    @JvmStatic
    fun recoverInterruptedRestoreUnderConfigLock(): Boolean {
        val journalFile = File(RESTORE_JOURNAL_PATH)
        if (!journalFile.exists()) return true
        if (!journalFile.isFile) {
            throw IOException("Restore journal path is not a regular file")
        }
        val journal = try {
            JSONObject(journalFile.readText())
        } catch (e: Exception) {
            throw IOException("Restore journal is unreadable", e)
        }
        if (journal.optInt("version", -1) != RESTORE_JOURNAL_VERSION) {
            throw IOException("Unsupported restore journal version")
        }
        val priorConfig = journal.optJSONObject("priorConfig")
            ?: throw IOException("Restore journal has no prior config")
        val priorDid = didSnapshotFromJournal(journal)

        val bridge = credentialFreeBridge(priorConfig)
        if (!UnifiedConfigManager.saveConfig(bridge, /* force = */ true)) {
            throw IOException("Could not publish credential-free rollback bridge")
        }
        if (!restoreDidSnapshot(priorDid)) {
            throw IOException("Could not restore prior DID")
        }
        if (!UnifiedConfigManager.saveConfig(
                JSONObject(priorConfig.toString()), /* force = */ true)) {
            throw IOException("Could not restore prior config")
        }
        clearRestoreJournal()
        Log.w(TAG, "Recovered interrupted config/DID restore")
        return true
    }

    private fun beginBundledDidTransition(
        value: String,
        priorDid: DidSnapshot,
        priorConfig: JSONObject,
    ): DidWriteResult {
        val single = value.lineSequence().firstOrNull()?.trim() ?: ""
        if (single.isEmpty()) {
            Log.w(TAG, "Bundled device-id is empty; credential sections will be kept")
            return DidWriteResult(usable = false, changed = false)
        }
        val bytes = single.toByteArray(StandardCharsets.UTF_8)
        if (priorDid.existed && priorDid.bytes.contentEquals(bytes)) {
            return DidWriteResult(usable = true, changed = false)
        }

        return try {
            writeRestoreJournal(priorDid, priorConfig)
            if (!UnifiedConfigManager.saveConfig(
                    credentialFreeBridge(priorConfig), /* force = */ true)) {
                throw IOException("Could not publish credential-free restore bridge")
            }
            writeDidBytesAtomic(bytes)
            Log.i(TAG, "Restored device-id from bundle")
            DidWriteResult(usable = true, changed = true)
        } catch (transitionFailure: Throwable) {
            if (File(RESTORE_JOURNAL_PATH).exists()) {
                try {
                    recoverInterruptedRestoreUnderConfigLock()
                } catch (rollbackFailure: Throwable) {
                    throw IOException(
                        "DID transition failed and rollback failed",
                        rollbackFailure,
                    )
                }
            }
            Log.w(TAG, "Could not restore device-id; credential sections will be kept")
            DidWriteResult(usable = false, changed = false)
        }
    }

    private fun credentialFreeBridge(root: JSONObject): JSONObject {
        val bridge = JSONObject(root.toString())
        for (section in CREDENTIAL_SECTIONS) bridge.remove(section)
        return bridge
    }

    private fun writeRestoreJournal(
        priorDid: DidSnapshot,
        priorConfig: JSONObject,
    ) {
        val didBytes = JSONArray()
        for (byte in priorDid.bytes) didBytes.put(byte.toInt() and 0xff)
        val journal = JSONObject()
            .put("version", RESTORE_JOURNAL_VERSION)
            .put("priorDidExisted", priorDid.existed)
            .put("priorDidBytes", didBytes)
            .put("priorConfig", JSONObject(priorConfig.toString()))
        writeAtomicFile(
            File(RESTORE_JOURNAL_PATH),
            journal.toString().toByteArray(StandardCharsets.UTF_8),
            worldAccessible = false,
            sequence = restoreJournalTempSequence.incrementAndGet(),
        )
    }

    private fun didSnapshotFromJournal(journal: JSONObject): DidSnapshot {
        val encoded = journal.optJSONArray("priorDidBytes")
            ?: throw IOException("Restore journal has no prior DID bytes")
        val bytes = ByteArray(encoded.length())
        for (i in 0 until encoded.length()) {
            val value = encoded.optInt(i, -1)
            if (value !in 0..255) {
                throw IOException("Restore journal has malformed DID bytes")
            }
            bytes[i] = value.toByte()
        }
        return DidSnapshot(
            existed = journal.optBoolean("priorDidExisted", false),
            bytes = bytes,
        )
    }

    private fun clearRestoreJournal() {
        val file = File(RESTORE_JOURNAL_PATH)
        if (!file.exists()) return
        if (!file.delete()) throw IOException("Could not clear restore journal")
        val parent = file.parentFile
            ?: throw IOException("Restore journal parent is unavailable")
        syncDidDirectory(parent)
    }

    private fun readDidSnapshotStrict(): DidSnapshot {
        val f = File(DID_PATH)
        if (!f.exists()) return DidSnapshot(existed = false, bytes = ByteArray(0))
        if (!f.isFile) throw IOException("DID path is not a regular file")
        return try {
            DidSnapshot(existed = true, bytes = f.readBytes())
        } catch (e: Exception) {
            throw IOException("DID read failed", e)
        }
    }

    private fun didValue(snapshot: DidSnapshot): String? {
        if (!snapshot.existed) return null
        return String(snapshot.bytes, StandardCharsets.UTF_8)
            .lineSequence()
            .firstOrNull()
            ?.trim()
            ?.ifEmpty { null }
    }

    private fun restoreDidSnapshot(snapshot: DidSnapshot): Boolean {
        return try {
            if (snapshot.existed) {
                writeDidBytesAtomic(snapshot.bytes)
            } else {
                val file = File(DID_PATH)
                if (file.exists() && !file.delete()) {
                    throw IOException("Could not remove newly-created DID")
                }
                val parent = file.parentFile
                    ?: throw IOException("DID parent is unavailable")
                syncDidDirectory(parent)
            }
            true
        } catch (rollbackFailure: Throwable) {
            Log.e(TAG, "DID rollback failed: ${rollbackFailure.message}", rollbackFailure)
            false
        }
    }

    private fun writeDidBytesAtomic(bytes: ByteArray) {
        val f = File(DID_PATH)
        writeAtomicFile(
            f,
            bytes,
            worldAccessible = true,
            sequence = didTempSequence.incrementAndGet(),
        )
    }

    private fun writeAtomicFile(
        file: File,
        bytes: ByteArray,
        worldAccessible: Boolean,
        sequence: Long,
    ) {
        val parent = file.parentFile
            ?: throw IOException("Atomic file parent is unavailable")
        val tmp = File(
            parent,
            "${file.name}.tmp.${android.os.Process.myPid()}.$sequence",
        )
        try {
            FileOutputStream(tmp).use { output ->
                output.write(bytes)
                output.flush()
                tmp.setReadable(true, !worldAccessible)
                tmp.setWritable(true, !worldAccessible)
                output.fd.sync()
            }
            if (!tmp.renameTo(file)) {
                throw IOException("Atomic file rename failed")
            }
            file.setReadable(true, !worldAccessible)
            file.setWritable(true, !worldAccessible)
            syncDidDirectory(parent)
        } finally {
            if (tmp.exists()) tmp.delete()
        }
    }

    private fun syncDidDirectory(directory: File) {
        var descriptor: java.io.FileDescriptor? = null
        try {
            descriptor = Os.open(
                directory.absolutePath,
                OsConstants.O_RDONLY or OsConstants.O_CLOEXEC,
                0,
            )
            Os.fsync(descriptor)
        } catch (e: ErrnoException) {
            if (e.errno != OsConstants.EINVAL
                    && e.errno != OsConstants.ENOSYS
                    && e.errno != OsConstants.ENOTSUP
                    && e.errno != OsConstants.EOPNOTSUPP) {
                throw IOException("DID directory fsync failed", e)
            }
        } finally {
            if (descriptor != null) {
                try {
                    Os.close(descriptor)
                } catch (_: Exception) {}
            }
        }
    }
}
